function meshPlot(meshData)
  clf;
  if strcmp(meshData.elementType, 'trig-cluster')
    hold on
    line([meshData.P(1,meshData.E(1,:)); meshData.P(1,meshData.E(2,:))], ...
      [meshData.P(2,meshData.E(1,:)); meshData.P(2,meshData.E(2,:))], ...
      'Color', [0.7,0.7,0.7]);
    ii = meshData.E(:,meshData.Interface);
    line([meshData.P(1,ii(1,:)); meshData.P(1,ii(2,:))], ...
      [meshData.P(2,ii(1,:)); meshData.P(2,ii(2,:))], ...
      'Color', 'k');
    hold off
  else
    line([meshData.P(1,meshData.E(1,:)); meshData.P(1,meshData.E(2,:))], ...
      [meshData.P(2,meshData.E(1,:)); meshData.P(2,meshData.E(2,:))], ...
      'Color', 'k');
  end
  axis off, axis equal;